name: Filebot Docker

on:
  pull_request:
  push:
    branches:
      - beta
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        
      - name: Docker meta
        id: metaraw
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/xd003/filebot:beta
          tags: |
            type=semver,pattern={{version}}
        
      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metaraw.outputs.tags }}
